server:
  port: 8765

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          okta:
            redirect-uri: http://localhost:4200/login
  cloud:
    gateway:
      routes:
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/vendor/**
          filters:
            - TokenRelay=
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - TokenRelay=
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - TokenRelay=



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-44580046.okta.com/oauth2/default
    audience: api://default
    client-id: 0oafxabpjx17KyfqO5d7
    client-secret: eqPcXbs7zqQAGk6pEW4oX5xDTvQBV6XdcddYK5gYutSd3g9m_qypgwq9gUZCRsMp
    scopes: openid, profile , email, offline_access ,internal


tokenEndpoint: https://dev-44580046.okta.com/oauth2/default/v1/token


logging:
  level:
    org.springframework.web: DEBUG
    com.fasterxml.jackson: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] #SB3"


management:
  tracing:
    sampling:
      probability: 1.0

# spring.cloud.gateway.discovery.locator.enabled=true