spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eventManagement
    username: postgres
    password: sdworld@456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-44580046.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oafxabpjx17KyfqO5d7
            client-secret: eqPcXbs7zqQAGk6pEW4oX5xDTvQBV6XdcddYK5gYutSd3g9m_qypgwq9gUZCRsMp
            redirect-uri: http://localhost:4200
        provider:
          okta:
            issuer-uri: https://dev-44580046.okta.com/oauth2/default


okta:
  oauth2:
    issuer: https://dev-44580046.okta.com/oauth2/default
    audience: api://default



server:
  port: 8000



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] #SB3"

